
   
name: Test
on:
  pull_request:
  push:
    branches:
      - main

jobs:
  test-unit:
    name: Test Units
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2.1.4
        with:
          go-version: '^1.18'
      - name: Run Unit Tests
        run:  make unit-test
  # test-sim:
  #   name: Test Simulations
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout source code
  #       uses: actions/checkout@v1
  #     - name: Run simulation tests
  #       uses: cedrickring/golang-action/go1.16@1.7.0
  #       env:
  #         GO111MODULE: "on"
  #       with:
  #         args: make test-sim-nondeterminism-fast
